version: '3.8'

services:
  db:
    image: mysql:8
    container_name: todolist_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tododb
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  api:
    build: ./api
    ports:
      - "4000:4000"
    container_name: todolist_api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: todouser
      DB_PASSWORD: todopass
      DB_NAME: tododb
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    container_name: todolist_front
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - frontend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        /sbin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  db_data:
  jenkins_home:

networks:
  backend:
    driver: bridge
  frontend:
